"""add checkin fields

Revision ID: 2fd461ce57e1
Revises: 16b45515c6ba
Create Date: 2026-07-21 19:00:49.559958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd461ce57e1'
down_revision = '16b45515c6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_discord_checkin', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pending_discord_reward', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_discord_reward')
        batch_op.drop_column('last_discord_checkin')

    # ### end Alembic commands ###
