"""add web checkin fields

Revision ID: a6277e1de135
Revises: 2fd461ce57e1
Create Date: 2026-07-21 19:37:07.604312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6277e1de135'
down_revision = '2fd461ce57e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_web_checkin', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pending_web_reward', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_web_reward')
        batch_op.drop_column('last_web_checkin')

    # ### end Alembic commands ###
