"""add enchant_info to shop_items

Revision ID: d1a8a159d616
Revises: d359b7445fd4
Create Date: 2026-08-02 19:23:51.011419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a8a159d616'
down_revision = 'd359b7445fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enchant_info', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_column('enchant_info')

    # ### end Alembic commands ###
